### ISSUE TITLE
Controller generation folder conflicts with starter:init

### ISSUE THREAD

**Issue by mwaa** [ralphowino/restful-api-helper#10]
in the config file we have controllers been generated under `Http\Controllers` but when i do `starter:init` i see that an `Api` folder is created and as some other classes. Can we have some consistency in this like sticking to the defaults and have `Http\Controllers\Api` as folder for controllers.

**Comment by samuelkubai** [comment]
This will be fixed with the initialization of the package during the setting of the paths
