### ISSUE TITLE
Restful flags when generating controller

### ISSUE THREAD

**Issue by mwaa** [ralphowino/restful-api-helper#7]
When generating controller can we add the ability to bypass the question on functions i would like to have.
1. a `restful` flag would be helpful in accomplishing this and place all function in class
2. a `restful-api` flag that would generally exclude `create and edit` functions i.e functions that only load views
3. the `starter:init` function generates a few traits for controllers. can we have `restful-trait` flag to automatically include the restful/resourceful trait in the controller generated. Alternatively flag can take value(class name) which generated controller will extend from. Ideally value should be of a controller that is already restful.
4. Also can we have default api functionality for all restful functions `index, store, update etc`. At the moment i have to select function i want and yet its generated blank. Rationale is that their is no advantage in me using restful-api-helper generate controller when i can use the Laravel's default `php artisan make:controller TaskController --resource`. This produces the same output making restful-api-helper unnecessary for this usecase. (Nice to have if i did an init and chose repository pattern. substitute functionality with appropriate repository function).

**Comment by samuelkubai** [comment]
Added the content to the controller methods and removed the traits. Makes a cleaner more sensible controller. Avoid misuse of the traits
